### ISSUE TITLE
Timeout issue in   page.waitForSelector('ul.nav .uib-tab:nth-child(2) a')

### ISSUE THREAD

**Issue by gkrishnaks** [LinusU/upload-opera-extension#4]
Hi
Faced a timeout issue with this line when I ran this from GitLab CI CD runner
https://github.com/LinusU/upload-opera-extension/blob/fcc8265e76a0e516daf299ac5ae6fc4e952126da/index.js#L26

Default timeout is 30000 and I tried adding timeout option to this line as 50000, and it still failed.  I guess opera addons page html might have changed and no longer have this selector, maybe. Can you please take a look at this - I will check this myself over the weekend. Thanks for this package

**Comment by gkrishnaks** [comment]
Turns out I was using "extensionID" - and not the package ID that shows up in URL. That's why I didn't work, closing this issue.

**Comment by LinusU** [comment]
Would be nice if we could catch that and give a nice error message though ☺️
